<?php

namespace CodeStepsBD\HistoryKeeper\Tests\Unit;

use CodeStepsBD\HistoryKeeper\Repositories\HistoryKeeperRepository;
use Tests\TestCase;


class ForTest extends TestCase
{

    public HistoryKeeperRepository $historyKeeperRepo;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->historyKeeperRepo = new HistoryKeeperRepository();
    }

    /**
     * A basic unit test example.
     */
    public function test_example(): void
    {

        $tableList = $this->historyKeeperRepo->getTableList(['users']);
        $this->assertFalse($tableList->contains('users'));
        $tableList = $this->historyKeeperRepo->getTableList([]);
        $this->assertTrue($tableList->contains('users'));

    }
}
